"use client";

import { useEffect,useMemo,useState } from "react";
import { driveFileName } from "@/lib/slugify";
import { guessCategoryId } from "@/lib/category-match";
import { uploadDriveFileInChunks } from "@/lib/upload-client";
import type { Book,BookMetadataResult,Category,Profile,UserBook } from "@/lib/types";

type Props={initialBooks:Book[];initialCategories:Category[];initialProfiles:Profile[];initialUserBooks:UserBook[]};
type Tab="livros"|"envios"|"aprovados"|"categorias"|"usuarios"|"drive";
const langName=(v?:string|null)=>({pt:"Português",en:"Inglês",es:"Espanhol",fr:"Francês",it:"Italiano",de:"Alemão",ja:"Japonês",zh:"Chinês",ru:"Russo"} as Record<string,string>)[v||""]||v?.toUpperCase()||"Idioma não informado";

export function AdminDashboard({initialBooks,initialCategories,initialProfiles,initialUserBooks}:Props){
  const [tab,setTab]=useState<Tab>("livros");const [books,setBooks]=useState(initialBooks);const [userBooks,setUserBooks]=useState(initialUserBooks);const [categories,setCategories]=useState(initialCategories);const [profiles,setProfiles]=useState(initialProfiles);const [message,setMessage]=useState("");const [uploading,setUploading]=useState(false);const [uploadProgress,setUploadProgress]=useState(0);const [title,setTitle]=useState("");const [epubFile,setEpubFile]=useState<File|null>(null);const [pdfFile,setPdfFile]=useState<File|null>(null);const [coverFile,setCoverFile]=useState<File|null>(null);const [suggestions,setSuggestions]=useState<BookMetadataResult[]>([]);const [searching,setSearching]=useState(false);const [selected,setSelected]=useState<BookMetadataResult|null>(null);const [drive,setDrive]=useState<{connected:boolean;accountEmail?:string|null;updatedAt?:string|null}>({connected:false});const [moderating,setModerating]=useState<string|null>(null);const [pendingPdfFiles,setPendingPdfFiles]=useState<Record<string,File|null>>({});const [pendingProgress,setPendingProgress]=useState<Record<string,number>>({});
  const computedEpubName=useMemo(()=>driveFileName(title,epubFile?.name),[title,epubFile?.name]);const computedPdfName=useMemo(()=>driveFileName(title,pdfFile?.name),[title,pdfFile?.name]);const suggestedCategory=selected?guessCategoryId(categories,selected.categories||[],selected.title,selected.description||""):null;
  const pending=userBooks.filter(b=>b.moderation_status==="pending");const approved=userBooks.filter(b=>b.moderation_status==="catalog");

  async function refreshDrive(){try{const r=await fetch("/api/drive/status",{cache:"no-store"});const d=await r.json();if(r.ok)setDrive(d);}catch{}}
  useEffect(()=>{refreshDrive();},[]);
  useEffect(()=>{if(selected&&title===selected.title){setSuggestions([]);return;}if(title.trim().length<2){setSuggestions([]);return;}const c=new AbortController();const t=setTimeout(async()=>{setSearching(true);try{const r=await fetch(`/api/book-metadata?title=${encodeURIComponent(title)}`,{signal:c.signal});const d=await r.json();if(r.ok)setSuggestions(d.results||[]);}catch{}setSearching(false);},450);return()=>{clearTimeout(t);c.abort();};},[title,selected]);
  function choose(item:BookMetadataResult){setSelected(item);setTitle(item.title);setSuggestions([]);}

  async function uploadCatalogFile(bookTitle:string,file:File,mimeType:string,onProgress:(value:number)=>void){
    const sr=await fetch("/api/drive/upload-url",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({title:bookTitle,originalFileName:file.name,mimeType,fileSize:file.size})});
    const s=await sr.json();if(!sr.ok){if(s.needsConnection)setTab("drive");throw new Error(s.error||"Falha ao preparar upload.");}
    const uploaded=await uploadDriveFileInChunks(s.uploadUrl,new File([file],file.name,{type:mimeType}),onProgress);
    return {id:uploaded.id,fileName:s.fileName as string};
  }

  async function addBook(formData:FormData){
    if(!epubFile||!pdfFile){setMessage("Selecione o EPUB original e o PDF de leitura.");return;}
    const validEpub=epubFile.name.toLowerCase().endsWith(".epub")||epubFile.type==="application/epub+zip";const validPdf=pdfFile.name.toLowerCase().endsWith(".pdf")||pdfFile.type==="application/pdf";
    if(!validEpub){setMessage("O arquivo original precisa ser EPUB.");return;}if(!validPdf){setMessage("O arquivo de leitura precisa ser PDF.");return;}
    setUploading(true);setUploadProgress(0);setMessage("");
    try{
      const author=String(formData.get("author")||selected?.author||"").trim();const description=String(formData.get("description")||selected?.description||"").trim();if(!author||!description)throw new Error("Autor e sinopse são obrigatórios.");
      const epub=await uploadCatalogFile(title,epubFile,"application/epub+zip",p=>setUploadProgress(Math.round(p*.5)));
      const pdf=await uploadCatalogFile(title,pdfFile,"application/pdf",p=>setUploadProgress(50+Math.round(p*.5)));
      let coverUrl=String(formData.get("cover_url")||selected?.coverUrl||"").trim();if(coverFile){const coverData=new FormData();coverData.append("file",coverFile);const cr=await fetch("/api/admin/covers",{method:"POST",body:coverData});const cd=await cr.json();if(!cr.ok)throw new Error(cd.error||"Não foi possível enviar a capa.");coverUrl=cd.coverUrl||coverUrl;}if(!coverUrl)throw new Error("Adicione uma capa para a versão Kindle.");
      const br=await fetch("/api/admin/books",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({title,author,description,language:String(formData.get("language")||selected?.language||""),year:String(formData.get("year")||selected?.year||""),pages:String(formData.get("pages")||selected?.pages||""),coverUrl,categoryId:String(formData.get("category_id")||"")||null,driveFileId:epub.id,fileName:epub.fileName,mimeType:"application/epub+zip",readingPdfDriveFileId:pdf.id,readingPdfFileName:pdf.fileName,published:formData.get("published")==="on",allowDownload:formData.get("allow_download")==="on"})});const saved=await br.json();if(!br.ok)throw new Error(saved.error||"Erro ao salvar livro.");setBooks(p=>[saved.book,...p]);setTitle("");setEpubFile(null);setPdfFile(null);setCoverFile(null);setSelected(null);setSuggestions([]);setUploadProgress(100);setMessage("Livro cadastrado com EPUB e PDF separados, sem conversão.");(document.getElementById("book-form") as HTMLFormElement|null)?.reset();
    }catch(e){setMessage(e instanceof Error?e.message:"Erro no upload.");}finally{setUploading(false);}
  }

  async function moderateUserBook(id:string,status:"pending"|"private"|"catalog"){
    setModerating(id);setMessage("");try{const r=await fetch("/api/admin/user-books",{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({id,status})});const d=await r.json();if(!r.ok)throw new Error(d.error||"Falha ao atualizar envio.");setUserBooks(p=>p.map(x=>x.id===id?{...x,...d.book}:x));setMessage(status==="catalog"?"Envio aprovado e movido para Aprovados.":status==="private"?"Envio marcado como privado; só o usuário continuará vendo.":"Envio voltou para análise.");}catch(e){setMessage(e instanceof Error?e.message:"Erro na moderação.");}finally{setModerating(null);}
  }

  async function attachPdfAndApprove(book:UserBook){
    if(book.reading_pdf_drive_file_id){await moderateUserBook(book.id,"catalog");return;}
    const file=pendingPdfFiles[book.id];if(!file){setMessage(`Selecione o PDF de leitura de “${book.title}” antes de aprovar.`);return;}
    if(!(file.name.toLowerCase().endsWith(".pdf")||file.type==="application/pdf")){setMessage("O arquivo de leitura precisa ser PDF.");return;}
    setModerating(book.id);setMessage("");setPendingProgress(p=>({...p,[book.id]:0}));
    try{
      const pdf=await uploadCatalogFile(book.title,file,"application/pdf",value=>setPendingProgress(p=>({...p,[book.id]:value})));
      const r=await fetch("/api/admin/user-books",{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({id:book.id,status:"catalog",readingPdfDriveFileId:pdf.id,readingPdfFileName:pdf.fileName})});const d=await r.json();if(!r.ok)throw new Error(d.error||"Falha ao aprovar envio.");setUserBooks(p=>p.map(x=>x.id===book.id?{...x,...d.book}:x));setPendingPdfFiles(p=>({...p,[book.id]:null}));setPendingProgress(p=>({...p,[book.id]:100}));setMessage("PDF anexado e livro aprovado com sucesso.");
    }catch(e){setMessage(e instanceof Error?e.message:"Erro ao anexar o PDF.");}finally{setModerating(null);}
  }

  async function removeUserBook(id:string){if(!confirm("Excluir este envio e remover os arquivos associados?"))return;setModerating(id);try{const r=await fetch(`/api/admin/user-books?id=${encodeURIComponent(id)}`,{method:"DELETE"});const d=await r.json();if(!r.ok)throw new Error(d.error||"Não foi possível excluir.");setUserBooks(p=>p.filter(b=>b.id!==id));setMessage("Envio excluído com sucesso.");}catch(e){setMessage(e instanceof Error?e.message:"Erro ao excluir envio.");}finally{setModerating(null);}}
  async function removeBook(id:string){if(!confirm("Remover este livro do catálogo?"))return;const r=await fetch(`/api/admin/books?id=${encodeURIComponent(id)}`,{method:"DELETE"});if(r.ok)setBooks(p=>p.filter(b=>b.id!==id));}
  async function addCategory(fd:FormData){const r=await fetch("/api/admin/categories",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({name:String(fd.get("name")||"")})});const d=await r.json();if(r.ok)setCategories(p=>[...p,d.category].sort((a,b)=>a.name.localeCompare(b.name)));else setMessage(d.error||"Erro ao criar categoria.");}
  async function removeCategory(id:string){const r=await fetch(`/api/admin/categories?id=${encodeURIComponent(id)}`,{method:"DELETE"});if(r.ok)setCategories(p=>p.filter(c=>c.id!==id));}
  async function updateUser(id:string,patch:{approved?:boolean;role?:string}){const r=await fetch("/api/admin/users",{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({id,...patch})});if(r.ok)setProfiles(p=>p.map(x=>x.id===id?{...x,...patch}:x));}
  async function connectDrive(){const r=await fetch("/api/drive/auth-url");const d=await r.json();if(r.ok&&d.url)location.href=d.url;else setMessage(d.error||"Não foi possível conectar o Drive.");}

  const uploadRows=(items:UserBook[],approvedMode=false)=><div className="table-list">{items.length?items.map(b=>{const hasPdf=Boolean(b.reading_pdf_drive_file_id&&b.reading_pdf_file_name);return <div className="table-row" key={b.id}><div style={{minWidth:0,flex:1}}><strong>{b.title}</strong><div className="meta">{b.author} • {langName(b.language)} • {b.uploader_name||b.uploader_email||"Usuário"} • {b.categories?.name||"Sem categoria"} • EPUB ✓ • {hasPdf?"PDF ✓":"PDF pendente"}</div>{!approvedMode&&!hasPdf&&<div className="stack" style={{marginTop:10,maxWidth:440}}><label>PDF de leitura<input type="file" accept=".pdf,application/pdf" onChange={e=>setPendingPdfFiles(p=>({...p,[b.id]:e.target.files?.[0]||null}))}/></label>{typeof pendingProgress[b.id]==="number"&&pendingProgress[b.id]>0&&<small className="muted">Upload do PDF: {pendingProgress[b.id]}%</small>}</div>}</div><div className="row wrap">{!approvedMode&&<><button className="btn" disabled={moderating===b.id} onClick={()=>attachPdfAndApprove(b)}>{hasPdf?"Aprovar":"Enviar PDF e aprovar"}</button><button className="btn secondary" disabled={moderating===b.id} onClick={()=>moderateUserBook(b.id,"private")}>Privado</button></>}{approvedMode&&<button className="btn secondary" disabled={moderating===b.id} onClick={()=>moderateUserBook(b.id,"private")}>Tornar privado</button>}<button className="btn danger" disabled={moderating===b.id} onClick={()=>removeUserBook(b.id)}>Excluir</button></div></div>}):<div className="muted">Nenhum livro nesta aba.</div>}</div>;

  return <><div className="tabs">{[["livros","Livros"],["envios",`Envios dos usuários (${pending.length})`],["aprovados",`Aprovados (${approved.length})`],["categorias","Categorias"],["usuarios","Usuários"],["drive","Google Drive"]].map(([k,l])=><button key={k} className={`tab ${tab===k?"active":""}`} onClick={()=>setTab(k as Tab)}>{l}</button>)}</div>{message&&<div className={`notice ${message.includes("sucesso")||message.includes("aprovado")||message.includes("cadastrado")||message.includes("privado")?"success":""}`} style={{marginBottom:16}}>{message}</div>}

  {tab==="livros"&&<div className="admin-grid"><section className="card panel"><h2>Adicionar livro</h2><form id="book-form" className="stack" action={addBook}>
    <label className="suggestion-box">Título<input value={title} onChange={e=>{setTitle(e.target.value);setSelected(null);}} placeholder="Digite título ou ISBN" required/><small className="muted">A busca prioriza edições em português, mas também mostra outros idiomas.</small>{searching&&<small className="muted">Buscando...</small>}{!!suggestions.length&&<div className="suggestions">{suggestions.map(i=><button type="button" className="suggestion" key={i.id} onClick={()=>choose(i)}>{i.coverUrl?<img src={i.coverUrl} alt=""/>:<span/>}<span><strong>{i.title}</strong><small>{i.author}{i.year?` • ${i.year}`:""} • {langName(i.language)}{i.description?" • com sinopse":""}</small></span></button>)}</div>}</label>
    <div className="file-preview">EPUB: <b>{computedEpubName}</b><br/>PDF: <b>{computedPdfName}</b></div>
    <label>EPUB original<input type="file" accept=".epub,application/epub+zip" onChange={e=>setEpubFile(e.target.files?.[0]||null)} required/><small className="muted">Arquivo original usado no Kindle e nos downloads EPUB. Não será convertido.</small></label>
    <label>PDF de leitura<input type="file" accept=".pdf,application/pdf" onChange={e=>setPdfFile(e.target.files?.[0]||null)} required/><small className="muted">Envie o PDF pronto exatamente como deve ser lido e baixado.</small></label>
    <label>Autor<input name="author" key={`a-${selected?.id||""}`} defaultValue={selected?.author||""} required/></label><label>Idioma<input name="language" key={`l-${selected?.id||""}`} defaultValue={selected?.language||""} placeholder="pt, en, es..."/></label>
    <div className="row"><label style={{flex:1}}>Ano<input name="year" type="number" key={`y-${selected?.id||""}`} defaultValue={selected?.year||""}/></label><label style={{flex:1}}>Páginas<input name="pages" type="number" key={`p-${selected?.id||""}`} defaultValue={selected?.pages||""}/></label></div>
    <label>Sinopse<textarea name="description" key={`d-${selected?.id||""}`} defaultValue={selected?.description||""} required/></label><label>URL da capa<input name="cover_url" key={`c-${selected?.id||""}`} defaultValue={selected?.coverUrl||""}/></label><label>Ou enviar capa<input type="file" accept="image/jpeg,image/png,image/webp,image/gif" onChange={e=>setCoverFile(e.target.files?.[0]||null)}/></label>
    <label>Categoria<select name="category_id" key={`cat-${selected?.id||"manual"}`} defaultValue={suggestedCategory||""}><option value="">Sem categoria</option>{categories.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select>{suggestedCategory&&<small className="muted">Categoria preenchida automaticamente a partir do livro escolhido.</small>}</label>
    <div className="row wrap"><label style={{display:"flex",alignItems:"center"}}><input name="published" type="checkbox" defaultChecked style={{width:"auto"}}/> Publicado</label><label style={{display:"flex",alignItems:"center"}}><input name="allow_download" type="checkbox" style={{width:"auto"}}/> Permitir download</label></div>{uploading&&<div className="file-preview">Upload: <b>{uploadProgress}%</b></div>}<button className="btn" disabled={uploading||!title||!epubFile||!pdfFile}>{uploading?"Enviando...":"Adicionar EPUB + PDF"}</button>
  </form></section><section className="card panel"><h2>Livros cadastrados</h2><div className="table-list">{books.length?books.map(b=><div className="table-row" key={b.id}><div><strong>{b.title}</strong><div className="meta">{b.author}{b.language?` • ${langName(b.language)}`:""} • EPUB: {b.file_name} • PDF: {b.reading_pdf_file_name||"não anexado"} • {b.published?"publicado":"oculto"}</div></div><button className="btn danger" onClick={()=>removeBook(b.id)}>Excluir</button></div>):<div className="muted">Nenhum livro cadastrado ainda.</div>}</div></section></div>}
  {tab==="envios"&&<section className="card panel"><h2>Envios dos usuários</h2><p className="muted">O usuário envia o EPUB e a capa. Anexe aqui o PDF de leitura correspondente para aprovar o livro no acervo.</p>{uploadRows(pending)}</section>}
  {tab==="aprovados"&&<section className="card panel"><h2>Aprovados</h2><p className="muted">Livros que possuem EPUB original e PDF de leitura separados.</p>{uploadRows(approved,true)}</section>}
  {tab==="categorias"&&<section className="card panel"><h2>Categorias</h2><form className="row" action={addCategory}><input name="name" placeholder="Nova categoria" required/><button className="btn">Adicionar</button></form><div className="table-list">{categories.map(c=><div className="table-row" key={c.id}><strong>{c.name}</strong><button className="btn danger" onClick={()=>removeCategory(c.id)}>Excluir</button></div>)}</div></section>}
  {tab==="usuarios"&&<section className="card panel"><h2>Usuários</h2><div className="table-list">{profiles.map(p=><div className="table-row" key={p.id}><div><strong>{p.full_name||p.email||"Usuário"}</strong><div className="meta">{p.email} • {p.role} • {p.approved?"aprovado":"aguardando"}</div></div><div className="row wrap"><button className="btn" onClick={()=>updateUser(p.id,{approved:!p.approved})}>{p.approved?"Bloquear":"Aprovar"}</button><button className="btn ghost" onClick={()=>updateUser(p.id,{role:p.role==="admin"?"reader":"admin"})}>{p.role==="admin"?"Tornar leitor":"Tornar admin"}</button></div></div>)}</div></section>}
  {tab==="drive"&&<section className="card panel" style={{maxWidth:700}}><h2>Google Drive</h2><div className="row"><span className={`status-dot ${drive.connected?"on":""}`}/><strong>{drive.connected?"Conectado de forma persistente":"Não conectado"}</strong></div>{drive.accountEmail&&<p className="muted">Conta: {drive.accountEmail}</p>}<p className="muted">A conexão fica salva no servidor e é renovada automaticamente.</p><div className="row wrap"><button className="btn" onClick={connectDrive}>{drive.connected?"Reconectar Google Drive":"Conectar Google Drive"}</button><button className="btn ghost" onClick={refreshDrive}>Verificar conexão</button></div></section>}</>;
}
