create extension if not exists pg_cron with schema pg_catalog;
create extension if not exists pg_net with schema extensions;

create table if not exists public.book_knowledge (
  id uuid primary key default gen_random_uuid(),
  canonical_key text not null unique,
  isbn text,
  title text not null,
  normalized_title text not null,
  author text not null,
  normalized_author text not null,
  description text,
  cover_url text,
  cover_urls text[] not null default '{}',
  language text,
  year integer,
  pages integer,
  subjects text[] not null default '{}',
  alternate_titles text[] not null default '{}',
  source text not null,
  source_ref text,
  confidence smallint not null default 0 check (confidence between 0 and 100),
  times_used integer not null default 0,
  last_used_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists book_knowledge_title_idx on public.book_knowledge(normalized_title);
create index if not exists book_knowledge_author_idx on public.book_knowledge(normalized_author);
create index if not exists book_knowledge_isbn_idx on public.book_knowledge(isbn) where isbn is not null;
create index if not exists book_knowledge_source_ref_idx on public.book_knowledge(source,source_ref) where source_ref is not null;
alter table public.book_knowledge enable row level security;

alter table public.books add column if not exists knowledge_id uuid references public.book_knowledge(id) on delete set null;
alter table public.books add column if not exists knowledge_confidence smallint;
alter table public.books add column if not exists knowledge_status text not null default 'pending';
alter table public.books add column if not exists knowledge_attempts smallint not null default 0;
alter table public.books add column if not exists knowledge_last_attempt_at timestamptz;
create index if not exists books_knowledge_queue_idx on public.books(published,metadata_reviewed,knowledge_status,knowledge_attempts,knowledge_last_attempt_at);

create table if not exists public.knowledge_runs (
  id bigint generated by default as identity primary key,
  started_at timestamptz not null default now(),
  finished_at timestamptz,
  requested_limit integer not null default 0,
  selected_count integer not null default 0,
  matched_count integer not null default 0,
  completed_count integer not null default 0,
  skipped_count integer not null default 0,
  error_count integer not null default 0,
  status text not null default 'running',
  note text
);
alter table public.knowledge_runs enable row level security;

create or replace function public.verify_knowledge_cron(p_secret text)
returns boolean language sql security definer set search_path=public,vault as $$
  select exists(select 1 from vault.decrypted_secrets where name='kindle_knowledge_cron_secret' and decrypted_secret=p_secret);
$$;
revoke all on function public.verify_knowledge_cron(text) from public,anon,authenticated;
grant execute on function public.verify_knowledge_cron(text) to service_role;

do $$
begin
  if not exists(select 1 from vault.secrets where name='kindle_knowledge_cron_secret') then
    perform vault.create_secret(gen_random_uuid()::text||gen_random_uuid()::text,'kindle_knowledge_cron_secret','Segredo interno do robô de conhecimento Kindle Books');
  end if;
end $$;

create or replace function public.trigger_knowledge_worker(p_limit integer default 50)
returns bigint language plpgsql security definer set search_path=public,extensions,vault,net as $$
declare request_id bigint; secret_value text;
begin
  select decrypted_secret into secret_value from vault.decrypted_secrets where name='kindle_knowledge_cron_secret' limit 1;
  if secret_value is null then raise exception 'knowledge cron secret missing'; end if;
  select net.http_post(
    url:='https://fsnpdtuzkayxngeltqdl.supabase.co/functions/v1/knowledge-worker',
    headers:=jsonb_build_object('Content-Type','application/json','X-Knowledge-Secret',secret_value),
    body:=jsonb_build_object('limit',least(greatest(coalesce(p_limit,50),1),100)),
    timeout_milliseconds:=120000
  ) into request_id;
  return request_id;
end;
$$;
revoke all on function public.trigger_knowledge_worker(integer) from public,anon,authenticated;
grant execute on function public.trigger_knowledge_worker(integer) to service_role;

do $$ declare r record; begin
  for r in select jobid from cron.job where jobname='kindle-knowledge-worker' loop perform cron.unschedule(r.jobid); end loop;
end $$;
select cron.schedule('kindle-knowledge-worker','*/10 * * * *',$$select public.trigger_knowledge_worker(50);$$);
