import { AppShell } from "@/components/AppShell";

const faqs=[
  {q:"Como enviar um livro ao meu Kindle?",a:"Abra Enviar ao Kindle, escolha o livro e toque em Enviar ao Kindle. O sistema usa o EPUB original e incorpora a capa escolhida na cópia enviada ao Kindle. Depois toque em Compartilhar com Kindle e selecione o app Kindle no celular."},
  {q:"Qual formato eu posso enviar para a Biblioteca?",a:"Nos envios pessoais, envie o EPUB original e uma capa. O arquivo é preservado sem conversão. Quando uma versão PDF de leitura estiver disponível, ela aparece separadamente para leitura e download."},
  {q:"A Biblioteca converte PDF e EPUB?",a:"Não. EPUB e PDF são mantidos como arquivos separados. O EPUB original é usado para Kindle e o PDF disponível é exibido exatamente no formato em que foi fornecido."},
  {q:"Posso escolher outra capa para o Kindle?",a:"Sim. Sempre que tocar em Enviar ao Kindle, você poderá escolher uma capa disponível ou enviar uma nova imagem em JPG, PNG ou WEBP. A capa escolhida é incorporada à cópia EPUB enviada ao Kindle."},
  {q:"Consigo ler sem baixar?",a:"Sim. Quando o livro possui uma versão PDF de leitura, ela abre dentro do leitor da Kindle Book. O download só acontece quando você escolhe uma opção de download ou compartilhamento."},
  {q:"Por que o Kindle não aparece no menu de compartilhamento?",a:"Confira se o app Kindle está instalado no celular. No iPhone ou Android, abra Mais/Outros no menu de compartilhamento e habilite Kindle. Se o navegador não permitir compartilhar arquivos diretamente, a Biblioteca baixa o EPUB como alternativa para você abri-lo no Kindle."},
  {q:"Quem consegue ver o livro que eu enviei?",a:"O livro aparece em Minha Biblioteca e em Meus Envios. O status mostrado informa se ele ainda está em análise, se permanece privado ou se já está disponível no acervo."},
  {q:"O que significa Em análise?",a:"Significa que o envio foi recebido e ainda está sendo revisado antes de ficar disponível no acervo geral. O livro continua aparecendo para você em Minha Biblioteca e em Meus Envios."},
  {q:"Onde ficam meus livros?",a:"Seus livros ficam vinculados à sua conta da Kindle Book. O acesso aos arquivos é controlado pelo sistema e cada usuário visualiza apenas o conteúdo permitido para sua conta."},
  {q:"Por que autor, idioma e sinopse são pedidos?",a:"Esses dados ajudam a identificar e organizar corretamente cada livro. Quando possível, a Biblioteca tenta preencher automaticamente título, autor, idioma, ano, páginas, categoria, sinopse e capa."},
  {q:"Meu upload falhou. O que devo verificar?",a:"Confirme se o arquivo é EPUB, se possui até 200 MB e se sua conexão está estável. Não feche a página durante o envio. Verifique também se uma capa foi selecionada."}
];

export default function HelpPage(){return <AppShell><main className="container help-page"><div className="page-head"><div><span className="eyebrow">CENTRAL DE AJUDA</span><h1>Precisa de ajuda?</h1><p>Respostas rápidas sobre leitura, privacidade, envios e Kindle.</p></div></div><section className="help-intro card panel"><div className="help-badge">?</div><div><h2>Como podemos ajudar?</h2><p className="muted">Toque em uma pergunta para abrir a resposta.</p></div></section><section className="faq-list">{faqs.map((item,index)=><details className="card faq-item" key={item.q} open={index===0}><summary>{item.q}<span>+</span></summary><div className="faq-answer">{item.a}</div></details>)}</section></main></AppShell>;}
